#!/bin/bash
set -e

pem_file="./drip-br-server-key.pem"
server_ip="13.53.66.106"

script_upload() {
  echo "upload... "
  rsync -Phave "ssh -i $pem_file" $1 ubuntu@$server_ip:$1
}

script_connect() {
  echo "connect... "
  ssh -i "$pem_file" ubuntu@$server_ip
}

script_download() {
  rsync -Phave "ssh -i $pem_file" ubuntu@$server_ip:$1 $1
}

script_replace() {
  echo "SCRIPT REPLACE INIT... "
  ssh -i "$pem_file" ubuntu@$server_ip 'bash -s ' <<EOF
  set -e
  d=`date '+%Y-%m-%d_%H-%M-%S'`
  name="api-backup-\$d"
  mv api \$name
  unzip api.zip -d api
  cd api
  npm install
  screen -X -S api quit 2>/dev/null || true
  screen -d -m -S api bash -c 'while true; do sudo node index.js >> log.log 2>> err.log; sleep 1; done'
EOF
}

script_pack__() {
  echo "START pack__... "
  dest="$2"
  dir="$3"
  if [ -d api/$dir ]; then
    rm -r api/$dir
  fi
  cp -r app/$dest api/$dir
  echo "END pack__... "
}

script_pack() {
  echo "INIT SCRIPT BACK... "
  cd api
  mv node_modules ..
  zip -r -9 api.zip *
  mv ../node_modules .
  mv api.zip ..
  cd ..
  if [ -n "${TESTE}" ]; then
    rm -r api/teste
  fi
}

while [ $# -gt 0 ]; do
  if [ "$1" = "clear" ]; then
    for x in "api.zip"; do
      if [ -f $x ]; then
        rm $x
      fi
    done
  elif [ "$1" = "pack" ]; then
    if [ "$2" = "app" ]; then
      script_pack $2
      shift
    else
      script_pack
    fi
  elif [ "$1" = "replace" ]; then
    script_replace
  elif [ "$1" = "upload" ]; then
    script_upload $2
    shift
  elif [ "$1" = "connect" ]; then
    script_connect
  elif [ "$1" = "download" ]; then
    script_download $2
    shift
  elif [ "$1" = "auto" ]; then
    echo "INIT script_upload api.zip"
    script_upload api.zip
    echo "END script_upload api.zip"

    echo "INIT script_replace"
    script_replace
    echo "END script_replace"
  elif [ "$1" = "api" ]; then
    script_pack
    script_upload api.zip
    script_replace
  elif [ "$1" == "-h" ]; then
    echo "Commandos: "
    echo " pack      : Cria o zip do api"
    echo " clear     : Apaga api.zip"
    echo " replace   : No servidor, substitui o código atual pelo api.zip que deve estar em ~"
    echo " connect   : Conecta ao servidor"
    echo " upload X  : Faz upload de X pro servidor"
    echo " download X: Faz download de X do servidor"
  else
    echo -e "\n\n\nComando desconhecido: $1\n"
    exit 1
  fi
  shift
done
